version: "3.8"

# compose file

services:
  web:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - .:/app

  tests:
    build: .
    command: ["./entrypoint.sh"]
    volumes:
      - .:/app
    depends_on:
      - web